version: '3.8'
volumes:
  mongo_data:
  shoppr_data:

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017
    env_file:
      - .env.shoppr

  shoppr:
    image: ghcr.io/laszloekovacs/shoppr-remix:latest
    container_name: shoppr
    volumes:
      - shoppr_data:/app/public/uploads
    ports:
      - 3000:3000
    depends_on:
      - mongo
    env_file:
      - .env.shoppr
